name: Production Deployment

on:
  push:
    branches: [main]

jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Repo
        uses: actions/checkout@v2

      - name: Copy updated files
        uses: appleboy/scp-action@v0.1.3
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          source: ./
          target: ./interrogation


      - name: Rebuild project
        uses: appleboy/ssh-action@master
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER}}
          port: 22
          command_timeout: 60m
          script: |
            sh interrogation/scripts/deploy.sh